#         ┌───────────┐
#         │b_10       │
#         │           │
#         │     apbm  │
#         └───────┬───┘
#                 │    
#         ┌───────▼───┐
#         │     apbs  │
#         │       ▼   │
#         │b_11  mem  │
#         └───────────┘
---
config:
  prj_dir: <path to avmium project>
  top_dir: <path to the target directory>
  top: apb_apb
  sim_clk_cycles: 28
  wavedump: 1
---
def_mod:                                        
  name: b_10                                    
  port:                                         
    name: apbm                                  
    proto: apb                                  
    dir: master                                 
---                                             
def_mod:                                        
  name: b_11                                    
  memmap:                                       
    mem:                                        
      addr: 0x0
      size: 100
  port:
    name: apbs
    proto: apb
    dir: slave
---
def_mod:
  name: apb_apb
  if:
    name: apbif
    proto: apb
  mod:
    name: b10
    type: b_10
    conn:
      apbm: apbif
  mod:
    name: b11
    type: b_11
    conn:
      apbs: apbif
